deployment:
  tasks:
    - export DEPLOYMENT_SOURCE=/home/ypeu7n1sin5q/repositories/MESCALESCA
    - export DEPLOYMENT_DEST=/home/ypeu7n1sin5q/public_html
    - /bin/cp -R $DEPLOYMENT_SOURCE/* $DEPLOYMENT_DEST/